### PR TITLE
Task3 rest

### PR DESCRIPTION
**Pull request by GuramSalia**
All tasks are done, except tests

### CODE REVIEW

**Comment by SiarheiBor** [comment]
Please document your controller like:
 @Operation(summary = "Register training")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Sucessfully registered"),
            @ApiResponse(responseCode = "404", description = "Trainee or trainer could not be found")})

**Comment by SiarheiBor** [comment]
if (traineeOptional.isEmpty()) {
            throw new InvalidRequestBodyException("Could not find trainee");
        }
Is it better to check on service level , because controller should not contains any business logic

**Comment by SiarheiBor** [comment]
Aspect is acceptable solution , but you can also take a look on https://www.baeldung.com/spring-boot-add-filter

**Comment by SiarheiBor** [comment]
Please recheck the status codes for different http methods : for example: 
HTTP DELETE Response Codes A successful response MUST be 200 (OK) if the server response includes a message body, 202 (Accepted) if the DELETE action has not yet been performed, or 204 (No content) if the DELETE action has been completed but the response does not have a message body.

**Comment by GuramSalia** [comment]
requested changes performed:
1. Controllers documented (with annotations)
2. Exceptions checked in Service Layer
3.  - Filter: not yet checked, will do later
4. status codes corrected

File attached, which I used to check the endpoints
[test endpoints.txt](https://github.com/GuramSalia/lab-task-spring-core/files/14658050/test.endpoints.txt)

**Comment by GuramSalia** [comment]
- changed package name 'payload' to 'api';
- changed POST mapping to GET mapping as requested in the task.

**Pull request merged**
